name: JLMTR_High_Frequency_Renew
on:
  schedule:
    - cron: '*/8 * * * *'  # 每 8 分鐘自動執行一次，防範 10 分鐘自動關機
  workflow_dispatch:      # 允許手動點擊按鈕執行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: 安裝必要組件
        run: pip install requests
      - name: 執行 JLMTR 續期任務
        env:
          FALIX_EMAIL: ${{ secrets.FALIX_EMAIL }}
          FALIX_PASSWORD: ${{ secrets.FALIX_PASSWORD }}
        run: python renew.py
